### ISSUE TITLE
Unsatisfied Link Error

### ISSUE THREAD

**Issue by projectilefish** [martinmarinov/TempestSDR#2]
I know your not supporting this anymore, but I get this error when trying to run the .jar file in Windows. Any ideas?

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: martin.tempest.core.TSDRLibrary.init()V
        at martin.tempest.core.TSDRLibrary.init(Native Method)
        at martin.tempest.core.TSDRLibrary.<init>(TSDRLibrary.java:207)
        at martin.tempest.gui.Main.<init>(Main.java:186)
        at martin.tempest.gui.Main$1.run(Main.java:165)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Extrathestral64** [comment]
Same here
