### ISSUE TITLE
HackRF support?

### ISSUE THREAD

**Issue by Brett99** [martinmarinov/TempestSDR#8]
Is it possible to use this with the hackrf?

**Comment by rtlsdrblog** [comment]
I haven't tested it but a HackRF ExtIO should work e.g. https://github.com/jocover/ExtIO_HackRF.

**Comment by hackliu** [comment]
Hi!
Every time I try to run the .JAR file release I get the error.

D:\JavaGUI>java -jar JTempestSDR.jar
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: martin.te
mpest.core.TSDRLibrary.init()V
        at martin.tempest.core.TSDRLibrary.init(Native Method)
        at martin.tempest.core.TSDRLibrary.<init>(TSDRLibrary.java:207)
        at martin.tempest.gui.Main.<init>(Main.java:186)
        at martin.tempest.gui.Main$1.run(Main.java:165)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)


Any help with the error? Thanks.

**Comment by AkechiShiro** [comment]
Is it possible to use this under Linux because the DLL I believe is only useful under Windows
